version: "3.9"

services:
  app:
    build: .
    image: hotel-search-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
